config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :users, except: :new
  resources :todos

  root "pages#home"

  get "/..." , to: "pages#home"
  get  "/about" , to: "pages#about"
  get "/help", to: "pages#help"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  # primary_abstract_class
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user
  default_scope { order(start_dt: :ASC) }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  before_save {self.mail = mail.downcase}
  validates :name, presence: true
  validates :mail, presence: true, uniqueness: true
  validates_format_of :mail, with: URI::MailTo::EMAIL_REGEXP

  has_many :todos, dependent: :destroy
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  with: :exception
  helper_method :current_user, :logged_in?, :isadmin?

  protected
    def current_user
      if session[:user_id]
        begin
          @current_user = User.find_by(id: session[:user_id])
        rescue ActiveRecord::RecordNotFound => e
          redirect_to root_path
        end
      end
    end

    def logged_in?
      !!current_user
    end

    def isadmin?
      if logged_in? && @current_user.isadmin?
        return true
      end
    end

    def require_user
      if !logged_in?
        flash[:alert] = 'Access denied. Please login first!'
        redirect_to signin_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  def about
  end
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(mail: params[:mail])
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to todos_path
      else
        flash[:danger] ="Invalid User or Password. Try again"
        render "signin"
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :require_user
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  before_action :set_user, only: [:create, :edit, :update, :destroy]

  def index
    # debugger
    if !isadmin?
      @todos = @current_user.todos
    else
      @todos = Todo.all
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = @current_user.id
    if  @todo.save
        flash[:notice] = "Post is created"
        redirect_to todo_path(@todo)
    else
      render "index"
    end
  end

  def show
    @read_only = true
    set_todo
  end

  def edit
    if Todo.exists?(params[:id])
      @read_only = false
    else
      flash[:alert] = "Post isn't found!"
      redirect_to todos_path
    end
  end

  def update
    if  @todo.update(todo_params)
        flash[:notice] = "Post is updated"
        redirect_to todo_path(@todo)
    else
      render "edit"
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = "Post is Deleted"
      redirect_to todos_path
    else
      render "index"
    end
  end

  def complete
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_param)
      flash[:success] = 'Recipe updated successfully'
      # redirect_to recipes_path
    end
  end

  private

    def set_user
      if session[:user_id]
        @user = User.find_by(id: session[:user_id])
      end
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end
    def todo_params
      params.require(:todo).permit(:name, :description, :start_dt, :end_dt, :iscompleted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only:[ :update, :edit]
  before_action :set_user, only: [:show, :update, :edit, :destroy]
  before_action :require_admin, only:[ :destroy ]

  def index
    if isadmin? && logged_in?
      @users = User.all
    elsif logged_in?
      set_user
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User Created!'
      session[:user_id] = @user.id
      redirect_to todos_path
    else
      flash[:error] = 'Error in Creation'
      render "new"
      end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User updated'
    else
      flash[:error] = 'failed to update'
    end
    redirect_to users_path
  end

  def destroy
    if @user.isadmin?
      flash[:error] = "Admin User. Can't be deleted"
    else
      if @user.delete
        flash[:success] = 'User removed!'
      else
        flash[:error] = 'Error in Creation'
      end
    end
    redirect_to users_path
  end


  private
    def set_user
      if session[:user_id]
        @user = User.find_by(id: params[:id])
      end
    end

    def require_user
      if @current_user  != @user
        redirect_to signin_path
      end
    end

    def user_params
      params.require(:user).permit(:name,:mail,:password, :password_confirmation)
    end

    def require_admin
      if !isadmin? && !logged_in?
        flash[:error] = 'Admin functionality. Please check your access!'
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<%# <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%# <strong><%= msg %>
  <%# <button type="button" class="close" data-dismiss="alert" aria-label="Close"> %>
    <%# <span aria-hidden="true">&times;</span> %>
  <%# </button> %>
<%# </div> %>
<% end %>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg bg-light">
      <%= link_to "Home", root_path ,class:"navbar-brand btn-light"%>
      <ul class="nav navbar-nav navbar-right ">
        <% if logged_in? %>
          <% if isadmin? %>
          <li>
            <h3 style="color: red;"> You are logged in as Admin! </h3>
          </li>
            <li class="nav-item btn btn-light" >
              <%= link_to "All Users", users_path%>
            </li>
          <% end %>
        <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle btn-lg" href="#" id="navbarNavDropdown" role="button" data-bs-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">  ToDos </a>
            <ul class="dropdown-menu">
              <li class="dropdown-item btn-focus" ><%= link_to "All ToDo", todos_path %></li>
              <li class="dropdown-item btn-focus"> <%= link_to "New ToDo",  new_todo_path %></li>
              <li class="dropdown-item btn-focus"><a href="#" >Something else here</a></li>
             </ul>
        </li>
          <li class="nav-item btn btn-float-right btn-lg" >
            <%= link_to "Sign Out", signout_path ,method: :delete%>
          </li>
        <%else%>
          <%# <li class="nav-item btn btn-float-right" >
            <%= link_to "Sign Up", signup_path ,class: "btn btn-success btn-lg" %>
          <%# </li>
          <li class="nav-item btn btn-float-right" >
            <%= link_to "Sign in", signin_path ,class: "btn btn-secondary btn-signout btn-lg" %>
          <%# </li> %>
        <%end%>
        <li class="nav-item btn btn-float-right btn-lg" >
          <%= link_to "About", about_path%>
        </li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoish</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render "layouts/navbar" %>
  <%= render "layouts/flash" %>
  </head>
    <div class="container">
      <body class="bg-color">
        <%= yield %>
      </body>
    </div>
  <footer class="footer mt-auto py-3">
    <div>
      <span class="text-muted">This is a rails page</span>
      <span class="text-muted pull-right"><%= link_to "back to home page", root_path%></span>
    </div>
  </footer>
</html>

app/views/pages/about.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel" style="text-align: left;">
  <u><h1 style="text-align: center;"> About Me </h1></u>
  <p>
    Hello Viewer! <br/>
    I'm Rajendran, a Computer Science Engineering graduate, looking for Project management Role
    and as a Rails Developer.<br/>
    I have over 11+ Years of experience in IT industry. In my first 10 years, I worked as an ERP Application Developer
    in serviced based industry with domain knowledge in Retail Industry and business process.<br/>
  </p>
  <p>
  <u><H4 style="text-align: center;"> Whats New ?</h4></u>
    I've always wondered what is beyond ERP and how to be a part of it. So I started to learn web based technologies and high level
    languages. <br/>
    Initially I started with Python and possess intermediate knowledge in python Pandas,numpy and scikit.<br/>
  </p>

  <p>
    Currently I am working on Ruby on Rails framework  with very good understanding and workings of the framework.<br/>
    I have very good understanding of DevOps life-cycle and various Tools.
    My approach to code is Test Driven Development. <br/>
  </p>

  <u><H4 style="text-align: center;"> DB &Tools </h4></u>
    Expert in MySQL. Git for versioning, Docker for images, jenkins for CI/CD
    and AWS for hosting the application.<br/> knowledge in ElasticSearch and Kubernetes.
    I have very good understanding of NOSQL as well.<br>
    My hobby projects are hosted in Heroku!
  <p>
  <u><H4 style="text-align: center;"> Learning and certifications </h4></u>
    I have completed <%= link_to "Project Management", asset_path("Coursera_pm.pdf") %>   course provided by Coursera in colloboration with Google. My Other certifications
    are <%= link_to "Ruby on Rails", asset_path("Udemy_RoR.pdf") %>  and <%= link_to "Kubernetes basics ", asset_path("Udemy_k8s.jpg") %> by Udemy.<br/>
  </p>

  <p>
  <u><H4 style="text-align: center;"> Hobby </h4></u>
   I like football and cycling. I love to read books as they give me another perspective.
   I try to get up early so i can jog in lakeshore nearby.
  </p>

</div>

app/views/pages/help.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
<h1> Help project </h1>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h2 class="display-4">Hello, All!</h2>
  <p class="lead">This is a web page with useful free services.</p>
  <img src=<%= asset_path("ny.jpg") %> class="img-fluid">
  <hr class="my-4">
  <p>So far we have ToDoish</p>
  <p>in Pipeline, we have timesheet, calendar and much more</p>
  <% if !logged_in?%>
  <%= link_to "New User? Sign up now! ", signup_path, class:"btn btn-primary" %>
  <%= link_to "Existing User? Sign in", signin_path, class:"btn btn-success" %>
  <%end %>
</div>

app/views/todos/_form.html.erb
<% if @todo.errors.any?%>
  <h2> Errors returned </h2>
  <%@todo.errors.full_messages.each do |msg|%>
  <li><%= msg%></li>
  <% end %>
<% end %>
<%= form_with(model: @todo) do |form| %>
  <p>
  <br/>
  <div class="card">
    <div class="card-header">
      <h3>ToDo</h3>
    </div>
    <%= form.text_field :name , class: "card-title",disabled: @read_only%>
  <p>
      <div class="card-body">
        <%= form.label :description, "What are all To Do ?", disabled: @read_only %>
      <br/>
        <%= form.text_area :description,class:"card-text", size: "60x10",disabled: @read_only %>
      <br/>
    <div class="sameline">
        <%= form.label :start_dt, "Started ?" %>
        <%= form.date_field   :start_dt ,disabled: @read_only%>
        <%= form.label :end_dt, "Done ?" %>
        <%= form.date_field   :end_dt, disabled: @read_only %>
        <%= form.label :iscompleted, "Is it Realllly Done?" %>
        <%= form.check_box  :iscompleted, disabled: @read_only%>
      </div>
      <br/>
    </p>
      <%if @todo.created_at? %>
          <div class="card-footer text-muted">
          <span>created at: <%=  time_ago_in_words(@todo.created_at) %> ago</span>
          </div>
      <%end%>
      <%= form.submit(@todo.new_record? ? "Create ToDo" : "Update ToDo", class: "btn btn-success" )  %>
    </p>
  </div>
<% end %>

app/views/todos/dontwant.html.erb
<table>
  <tr>
    <th>Todo</th>
    <th>What to do</th>
  </tr>
 <tr>
    <td><%= todo.name%></td>,class:"btn btn-primary"
    <td><%= todo.description%></td>
    <td><%= link_to "Show", todo_path(todo.id),class:"btn btn-primary" %></td>
    <td><%= link_to "Edit", edit_todo_path(todo.id, ,class:"btn btn-primary") %></td>
    <td><%= button_to "Delete",data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-primary" %></td>
    <br/>
  </tr>
</table>

app/views/todos/edit.html.erb
<div class= "container-fluid" style="background-color:lightgray;">
<%= render "form" %>
  <div class="sameline">
    <%= link_to "Back", todos_path , class: "btn btn-info" %>
    <%= link_to "Delete", todo_path(@todo), method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/todos/index.html.erb
<div>
  <table class="table table-hover table-bordered">
  <h2 style="text-align :center;"> All ToDos </h2>  <br/>
    <tr>
      <th class="th-text">ToDo</th>
      <th class="th-text">What to do</th>
      <th class="th-text">Start ?</th>
      <th class="th-text">End ?</th>
      <th class="th-text">Done ?</th>
      <th class="th-text">Edit</th>
      <th class="th-text">Delete</th>
    </tr>
    <% if @todos.size <= 0%>
      <h3> No Todos yet</h3>
    <% else %>
      <% @todos.each do |todo| %>
      <tr>
        <td class="td"><%= link_to todo.name, todo_path(todo.id), :style => 'width: 100%;' , class: "btn btn-light" %></td>
        <td><%= todo.description%></td>
        <td><%= todo.start_dt%></td>
        <td><%= todo.end_dt%></td>
        <td><%= check_box :iscompleted,  todo.iscompleted, disabled: :true %></td>
        <td><%= link_to "Edit", edit_todo_path(todo.id), class: "btn btn-info" %></td>
        <td><%= button_to "Delete", todo_path(todo.id), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
    <% end %>
  </table>
  </div>

app/views/todos/new.html.erb
<div class= "container-fluid">
  <%= render "todos/form" %>
<div>
<%= link_to "Back", todos_path , class: "btn btn-info"%>
</div>

app/views/todos/show.html.erb
<div>
<%= render "todos/form" %>
<div>
  <tfoot class="sameline btn btn-info" >
    <td><%= link_to "Back", todos_path, class: "btn btn-info" %></td>
    <td><%= link_to "Edit", edit_todo_path(@todo.id), class: "btn btn-primary" %> </td>
    <td><%= link_to "Delete", todo_path(@todo.id), method: :delete, class: "btn btn-danger" %></td>
   </tfoot>
</div>

app/views/users/_form.html.erb
<div class="container">
  <% if @user.errors.any?%>
    <h2> Errors returned </h2>
    <% @user.errors.full_messages.each do |msg|%>
      <li><%= msg%></li>
    <% end %>
  <% end %>
</div>
<div class="text-center signin">
  <%= form_with model: @user, :html => { class:"form-signin w-100 m-auto" , role:"form"} do |form| %>
      <br/>
      <div class="container well">
        <div class="form-floating">
        <%= form.label :name %>
          <%= form.text_field :name, placeholder: 'user name', class:"form-control"%><br/>
        </div>
        <div class="form-floating">
        <%= form.label :mail %>
          <%= form.text_field :mail, placeholder: 'example@email.com', class:"form-control"%><br/>
        </div>
        <div class="form-floating">
          <%= form.label :password %>
          <%= form.password_field :password, placeholder: 'Enter password', class:"form-control" %>
        </div>
        <br>
        <div class="form-floating">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, placeholder: 'Re-enter password', class:"form-control" %>
        </div>
        <br>
          <%= form.submit(@user.new_record? ? "Sign Up" : "Update User", class: "btn btn-primary btn-lg")%>
      </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="form-floating">
    <h1> Edit user</h1>
</div>

<%= render "form" %>

app/views/users/index.html.erb
<table class="table table-hover">
<h2> All Users </h2>
  <tr>
    <th>User</th>
    <th>Email</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% if @users.size <= 0%>
    <h3> No Active Users </h3>
  <% else %>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user.id), :style => 'width: 100%;' , class: "btn btn-light" %></td>
      <td><%= user.mail%></td>
      <%# <td><%= check_box_tag todo.isadmin,"Admin" , todo.isadmin, disabled: true %></td>
      <td><%= link_to "Edit", edit_user_path(user.id), class: "btn btn-info" %></td>
      <% if !user.isadmin?%>
      <td><%= button_to "Delete", user_path(user), method: :delete, class: "btn btn-danger" %></td>
      <% end %>
    </tr>
  <% end %>
<% end %>
</table>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<div>
<h4> User  </h4>
<%= render "users/form" %>
<div>
  <tfoot>
    <td><%= link_to "Back", users_path, class: "btn btn-info" %></td>
    <td><%= link_to "Edit", edit_user_path(@user.id), class: "btn btn-info" %> </td>
    <td><%= button_to "Delete", user_path(@user.id), method: :delete, class: "btn btn-danger" %></td>
   </tfoot>
</div>